In [2]:
import numpy as np 
from sklearn.preprocessing import MinMaxScaler

#defining an array
df = np.array([[2,3,7,30],[9,4,6,1],[8,15,2,40],[20,10,2,6]])
print (df)

#normalizing the array

scaler = MinMaxScaler()
scaler.fit(df)
scaled_features = scaler.transform(df)
print(scaled_features)


[[ 2  3  7 30]
 [ 9  4  6  1]
 [ 8 15  2 40]
 [20 10  2  6]]
[[0.         0.         1.         0.74358974]
 [0.38888889 0.08333333 0.8        0.        ]
 [0.33333333 1.         0.         1.        ]
 [1.         0.58333333 0.         0.12820513]]


In [23]:
#standard Scalar
from sklearn.preprocessing import StandardScaler
import numpy as np
#defining an array
df = np.array([[2,3,7,30],[9,4,6,1],[8,15,2,40],[20,10,2,6]])
print(df)
sc_X= StandardScaler()
sc_X=sc_X.fit_transform(df)
print(sc_X)

[[ 2  3  7 30]
 [ 9  4  6  1]
 [ 8 15  2 40]
 [20 10  2  6]]
[[-1.19319056 -1.03142125  1.20740686  0.66200869]
 [-0.11547005 -0.825137    0.76834982 -1.12387522]
 [-0.26943013  1.44398974 -0.98787834  1.27783073]
 [ 1.57809074  0.4125685  -0.98787834 -0.8159642 ]]


In [25]:
from sklearn import datasets
import pandas as pd
iris = datasets.load_iris()
data = pd.DataFrame(iris.get('data'),columns=['sepal length','petal length','sepal width','petal width'])
data.head()
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data.iloc[:,:-1],data['sepal width'], test_size=0.33, random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()


In [36]:
from distutils import text_file
from inspect import getmodule
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv("iris.csv")
x=dataset[['sepal.length','petal.length','sepal.width','petal.width']]
y=dataset['variety']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.35)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.naive_bayes import GaussianNB
gmodel=GaussianNB()
gmodel.fit(x_train,y_train)
gpred=gmodel.predict(x_test)
print(gpred)

from sklearn.metrics import confusion_matrix
gcm = confusion_matrix(y_test,gpred)
print(gcm)

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,gpred)
print (accuracy)

print("Probabilities of falling into each class")
print(gmodel.predict_proba([[5,3,1.2,2]]))
print("input is classified into: ")
ans = gmodel.predict([[5,3,1.2,2]])
print(ans)

['Virginica' 'Versicolor' 'Setosa' 'Virginica' 'Versicolor' 'Versicolor'
 'Setosa' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Virginica'
 'Virginica' 'Setosa' 'Versicolor' 'Setosa' 'Versicolor' 'Versicolor'
 'Versicolor' 'Virginica' 'Virginica' 'Setosa' 'Setosa' 'Versicolor'
 'Setosa' 'Virginica' 'Setosa' 'Virginica' 'Versicolor' 'Versicolor'
 'Versicolor' 'Setosa' 'Setosa' 'Versicolor' 'Versicolor' 'Versicolor'
 'Setosa' 'Virginica' 'Setosa' 'Versicolor' 'Versicolor' 'Virginica'
 'Versicolor' 'Virginica' 'Virginica' 'Setosa' 'Virginica' 'Setosa'
 'Versicolor' 'Virginica' 'Virginica' 'Virginica' 'Versicolor']
[[14  0  0]
 [ 0 21  1]
 [ 0  2 15]]
0.9433962264150944
Probabilities of falling into each class
[[0.00000000e+00 2.17832999e-33 1.00000000e+00]]
input is classified into: 
['Virginica']
