In [2]:
import numpy as np
arr=np.array([10,20,30,40,50],dtype=int)
print (arr)

[10 20 30 40 50]


In [4]:
#There are several ways in which arrays in numpy can be created

# 1. Using linspace()
#Syntax: linspace(start,stop,n)

arr=np.linspace(0,20,6)
print(arr)

# 2. Using logspace()
#Syntax: logspace(start,stop,n)

arr=np.logspace(1,4,5) #This function represents values starting from 10^1 to 10^4
print(arr) 
#3. Using arange()
# Syntax: arange(start,stop,stepsize)
arr2=np.arange(5,10)
print(arr2)

#4. Using zeros() and ones()
#Syntax: zeros(n,datatype)
#Syntax: ones(n,datatype)
zarr=np.zeros(5,int)
narr=np.ones(5,int)
print(zarr)
print(narr)

[ 0.  4.  8. 12. 16. 20.]
[   10.            56.23413252   316.22776602  1778.27941004
 10000.        ]
[5 6 7 8 9]
[0 0 0 0 0]
[1 1 1 1 1]


In [10]:
import numpy as np
import math
#Performing arithmetic operations with arrays
arr=np.array([10,20,30,5,-40])
print("After adding 5: ",arr+5)
print("After Subtracting 5: ",arr-5)
print("After Multiplying 5: ",arr*5)
print("After Dividing with 5: ",arr/5)
print("After Modular Division with 5: ",arr%5)

#Performing expression in arrays
print("Expression values: ",(arr+5)**2-10)

#some math functions
values=np.array([0,math.pi/2,math.pi/3,math.pi/4,math.pi/6,np.pi])
print("Sin values",np.sin(values))
print("Cos values",np.cos(values))
print("Tan values",np.tan(values))
print("Biggest Value: ",max(arr))
print("Minimum Value: ",min(arr))
print("Sum of all elements: ",sum(arr))
print("Sorting the array: ",np.sort(arr))
print("Mean: ",np.mean(arr))
print("Median: ",np.median(arr))
print("Square root: ",np.sqrt(arr))
print(np.prod(arr))
print(np.std(arr))
print(np.var(arr))
print(np.cov(arr))

After adding 5:  [ 15  25  35  10 -35]
After Subtracting 5:  [  5  15  25   0 -45]
After Multiplying 5:  [  50  100  150   25 -200]
After Dividing with 5:  [ 2.  4.  6.  1. -8.]
After Modular Division with 5:  [0 0 0 0 0]
Expression values:  [ 215  615 1215   90 1215]
Sin values [0.00000000e+00 1.00000000e+00 8.66025404e-01 7.07106781e-01
 5.00000000e-01 1.22464680e-16]
Cos values [ 1.00000000e+00  6.12323400e-17  5.00000000e-01  7.07106781e-01
  8.66025404e-01 -1.00000000e+00]
Tan values [ 0.00000000e+00  1.63312394e+16  1.73205081e+00  1.00000000e+00
  5.77350269e-01 -1.22464680e-16]
Biggest Value:  30
Minimum Value:  -40
Sum of all elements:  25
Sorting the array:  [-40   5  10  20  30]
Mean:  5.0
Median:  10.0
Square root:  [3.16227766 4.47213595 5.47722558 2.23606798        nan]
-1200000
24.08318915758459
580.0
725.0


C:\Users\pjaas\AppData\Local\Temp\ipykernel_8752\1371052403.py:25: RuntimeWarning: invalid value encountered in sqrt
  print("Square root: ",np.sqrt(arr))


In [ ]:
"""
Comparison of Arrays

We can use relational operators (>,>=,<,<=,=,!=) to compare the arrays of the same size.
These operators compare the elements of the array and return another array with boolean values, it means the resultant array contains elements which are
true or false.

The any() can be used to determine if any one element of the array is true.
The all() can be used to determine whether all the elements in the array are true.
The logical_and(), logical_or() and logical_not() functions are useful to get the boolean array as a result of comparing the compund condition.
The where() can be used to create a new array based on whether the given condition is true or false.
"""