20-07-2022 
Matrix Library & Operations

The Numpy module consists of a matrix library. The numpy.matlib() is used in NumPy for matrix functions. These functions return matrix values as output. It uses the arrat elements as input.

In [3]:
import numpy as np
import numpy.matlib


#np.matlib.empty() returns a new matrix in which the entries are uninitialized. 
print(np.matlib.empty((5,3)))

[[6.23042070e-307 3.56043053e-307 1.37961641e-306]
 [8.90071135e-308 8.01097889e-307 1.78020169e-306]
 [7.56601165e-307 1.02359984e-306 1.33510679e-306]
 [2.22522597e-306 6.23053614e-307 1.33511562e-306]
 [6.89805151e-307 2.56765117e-312 2.56765117e-312]]


In [6]:
#np.matlib.zeros() we use this function to initialize a new matrix. All the matrix elements are set to be zero
print(np.matlib.zeros(5))

[[0. 0. 0. 0. 0.]]


In [10]:
#np.matlib.ones()
print(np.matlib.ones((4,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
#np.numpy.eye() is used to initialize a matrix with 1 as the diagonal elements and 0 otherwise.
# mtlb.eye(n,m,k,dtype)
#n - represents the number of rows
#m - represents the number of columns
#k - denotes the index of the diagonal
#dtype - defines the datatype of the output matrix 

print(np.matlib.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
# np.matlib.rand() is used to initialize a matrix filled with random values . The size of the matrix is given as input.
print(np.matlib.rand(5))

[[0.01781842 0.91485407 0.23787241 0.05527442 0.84583652]]


In [15]:
#np.matlib.repmat(array,m,n) We take three arguments. The first one defines the array and the other two the axes
np.matlib.repmat(2,3,4)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [36]:
#np.matlib.randn() dwith the use of this function(), we can generate an array having random values from a standard normal distribution. We can specify the numner of elements as a parameter.
print(np.matlib.randn(5))

[[ 1.31476034 -1.07268541  1.57241123 -0.30279553  1.63455232]]


In [33]:
#np.matlib.matmul()
#The matrix multiplication function gives the multiplication of two matrices of same sahpe. If the shape is not the same, then it gives an Error

a=np.array([4,5,6])
b=np.array([7,8,9])
print(np.matmul(a,b))

122


Array Broadcasting

This matlib library is very useful for working with NumPy matrix. It takes the ndarray object as unpuy and returns the appropriate matrix.
These functions have additional functionality due to its input parameters. We can define the size, data type, shape and order of the resultant matrices.

The term broadcasting refers to the ability of Numpy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usuallly done one corresponding elements. If two arrays are of exact same shape, then these operations are smoothly performed.

In [35]:
#Example
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=a*b
print(c)

[ 5 12 21 32]


If the two dimensions ot the arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting
capability. The smaller array is broadcast to the size of the larger array so that they have compatable shapes.