In [5]:
import numpy as np

#This function computs complex conjugate or real symmetric matrices. The function returens two objects for eigenvalues and eigenvectors reespectively
# The Outputconsists og:
# A 1-D array object containing og eigenvalues
# A 2-D square matrix containing eigenvectors for each column 

#Function to calculate Eigen values and vector
a=np.array([[1,2,3],[3,2,-1],[4,0,-4]])
val,vect=np.linalg.eig(a)
print(val)
print(vect)

[-6.05798024  4.4666812   0.59129904]
[[ 0.44047381 -0.66326042  0.49735565]
 [-0.27023519 -0.67962995 -0.75158903]
 [-0.85612836 -0.31335084  0.43330277]]


In [3]:
#The linspace() outputs an equally spaced array. We use it for array generation 
np.linspace(0,10,num=4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [6]:
#The np.logspace() return numbers spaced evenly on a log scale. We use it for array generation.
np.logspace(0,10,num=4)

array([1.00000000e+00, 2.15443469e+03, 4.64158883e+06, 1.00000000e+10])

In [10]:
#For 1-D arrays the most common function is np.arange(..), passing any value create an array from 0 to that number
print(np.arange(20))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [9]:
#The np.asarray() is to convert an input to array. It is helpful in array creation.
np.asarray([1,2,3,4])

array([1, 2, 3, 4])