20-07-2022 
Matrix Library & Operations

The Numpy module consists of a matrix library. The numpy.matlib() is used in NumPy for matrix functions. These functions return matrix values as output. It uses the arrat elements as input.

In [3]:
import numpy as np
import numpy.matlib


#np.matlib.empty() returns a new matrix in which the entries are uninitialized. 
print(np.matlib.empty((5,3)))

[[4.67296746e-307 1.69121096e-306 7.56597091e-307]
 [8.34441742e-308 1.78022342e-306 6.23058028e-307]
 [9.79107872e-307 6.89807188e-307 7.56594375e-307]
 [6.23060065e-307 1.78021527e-306 8.34454050e-308]
 [1.11261027e-306 2.04712907e-306 3.49698923e-317]]


In [4]:
#np.matlib.zeros()

In [10]:
#np.matlib.ones()
print(np.matlib.ones((4,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
#np.numpy.eye()

In [12]:
#np.matlib.rand()

In [15]:
#np.matlib.repmat(array,m,n)
np.matlib.repmat(2,3,4)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [16]:
#no.matlib.randn()
np.matlib.randn()