In [1]:
import numpy as np

In [4]:
#np.around(array,decimals) returns the value rounded to the desired precision

a=np.array([1.0,5.55,123,0.567,25.532])
print("Original array: ",a)

print("After rounding: ")
print(np.around(a))
print(np.around(a,decimals=1))
print(np.around(a,decimals=-1))

Original array:  [  1.      5.55  123.      0.567  25.532]
After rounding: 
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


In [16]:
#np.floor returns the largest integer not greater than the input parameter.

b=np.array([-1.7,1.5,-0.2,0.6,10])
print("The given array: ",b)

print("After Flooring: ",np.floor(b))
print("After Ceiling: ",np.ceil(b))

The given array:  [-1.7  1.5 -0.2  0.6 10. ]
After Flooring:  [-2.  1. -1.  0. 10.]
After Ceiling:  [-1.  2. -0.  1. 10.]


In [15]:
#add(),subtract(), miltiply(), divide()
m=np.arange(9,dtype=np.float_).reshape(3,3)
n=np.array([10,10,10])

print("The array is: \n",m)
print("After Addition: \n",np.add(m,n))
print("After Subtration: \n",np.subtract(m,n))
print("After multiplication: \n",np.multiply(m,n))
print("After division: \n",np.divide(m,n))

The array is: 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
After Addition: 
 [[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
After Subtration: 
 [[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
After multiplication: 
 [[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]
After division: 
 [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
